### ISSUE TITLE
Needs to add checks for catalog data

### ISSUE THREAD

**Issue by shanosborne** [spacetelescope/jwst-fgs-countrate#11]
There's been an issue reported by @kjbrooks that sometimes there are cases of numbers from the GSC either 1) strings or 2) have multiple decimal points (just due to errors in the catalog). Need to add a check that values are floats, and if not try to cast them as floats.

Not sure if we want to auto-fix multiple decimal places because we may not be sure which decimal place to pick. But we could do it with a string split.

**Comment by DaftPict** [comment]
I just saw this comment in my email notifications. As the current lead on the GSC, I would appreciate more information about any errors you find so I can help resolve them for everybody rather you needing customized workarounds.

**Comment by kjbrooks** [comment]
Hi @DaftPict, I am finding multiple instances of pass band values from GSC queries coming back as strings (not floats as expected). Since `fgscountrate` is not currently checking types for magnitude values, this threw an error when those values were added to floats. I am seeing this in multiple instances, particularly because magnitudes are coming back with multiple periods in their numbers and these are automatically being seen as strings. 

Turns out this is happening far more often than I first realized so I am attaching some code that I would recommend that you run. For the code I am sending, this specific issue is for values coming from the 'FpgMag', 'JpgMag', 'NpgMag',  'tmassJmag', 'tmassHmag', and 'tmassKsmag' bands.

To run this, you will need to checkout the branch 'generalize_for_mirage' for this repository. I have added a check for strings (and allow the user to use `fgscountrate.fgs_countrate_core.FGSCountrate` in this way) in that branch and it will write to the terminal what the value is and the band that it is getting it from. I ran these lines in ipython.


    import fgscountrate

    data_frame = fgscountrate.utils.query_gsc(minra=273.0, maxra=273.1, mindec=65.42, maxdec=65.43) 

    for i in range(len(data_frame)): 
         print(i) 
         mini_data_frame = data_frame.iloc[i:i+1] 
         mini_data_frame = mini_data_frame.rename(index={i:0}) 

         for guider in [1, 2]: 
            fgs = fgscountrate.fgs_countrate_core.FGSCountrate(guide_star_id=None, guider=guider) 
            _, _, fgs_mag, fgs_mag_err = fgs.query_fgs_countrate_magnitude(data_frame=mini_data_frame)  

The index being printed indicates which row in `data_frame` this is coming from. 

Additionally, with a slightly different query (different RA and Dec), I am also seeing that in at least one case, the value retrieved from the 'SDSSgMagErr' band, while it looks like a float, when checking its type, it is actually a string.

**Comment by DaftPict** [comment]
Since it is impossible for the database to have multiple decimal points in a float field I suspect that the query must not be returning the correct data values/data types. Do you know how the query is performed? I'm still a git newbie so if possible just email me (mclean@stsci.edu) the query module and I can look at it??

**Comment by DaftPict** [comment]
ignore earlier comment - I figured out how to clone and did a quick test of the data_frame immediately after the query_gsc and the catalog data appear OK at that point so there must be a problem with the data_frame manipulation after that... I'll poke a bit more later.

**Comment by DaftPict** [comment]
It appears that the read_csv function is giving columns different datatypes because of missing data, e.g FpgMag becomes an object since it is sparsely filled but SDSSmags become floats since they are mostly filled. This seems to result in errors with subsequent dataframe operations. The multiple decimals result when the magnitude column and magnitude error column appear to become concatenated (don't understand why) when they are objects. Looking at the read_csv docs, if you add the argument na_values it will ignore the missing data when deriving the datatype. Since the query returns a single space for null data I did the following in the query_gsc function:

    try:
        data_frame = pd.read_csv(io.StringIO(request.decode('utf-8')), skiprows=1, na_values=[' '])
        #data_frame.replace(r'^\s+$', -999, regex=True, inplace=True)
    except pd.errors.EmptyDataError:
        raise NameError("No guide stars match these requirements in catalog {}".format(catalog))

and this appears to correctly set the datatypes of the magnitudes.  The missing values become NaN which python treats correctly which is better than the -999 for null data.

**Comment by kjbrooks** [comment]
@DaftPict I tried your suggestion with the same results as before, so I ado not think that is a complete solution.

**Comment by kjbrooks** [comment]
Just a note, when I check the values in data_frame (the result of `gsc_query`), they do not have the extra decimals, but they are still strings. I might be that there is something happening later that is causing the extra decimals, but there is still an issue with the original query returning strings instead of floats.

**Comment by kjbrooks** [comment]
@shanosborne so far I have see no issue at all with this change, including allowing missing vaules to be NaNs and not -999. (I am running the same code now on a data frame with over 10,000 entries and nothing has crashed yet after almost 4,000 objects) To solve this issue, I think the only other thing to consider is either keeping it as is so that all missing values go to -999, or replacing the -999 dependency with NaNs.

**Comment by kjbrooks** [comment]
I forgot to say this yesterday, thank you @DaftPict for tracking down this issue!!

**Comment by kjbrooks** [comment]
@shanosborne I forgot to move off this branch before running MAGIC and found that change (without additional work) does impacts MAGIC. Please see attached screen shot. It looks since the code is not looking for nans (in order to ignore them?), I can get nan as my FGS countrate. 

<img width="611" alt="Screen Shot 2020-06-05 at 3 03 14 PM" src="https://user-images.githubusercontent.com/17128221/83913913-36f41c00-a73e-11ea-9efc-85e4af7172a5.png">
